[package]
name = "vdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
flate2 = "1.0.33"
quick-xml = "0.36.1"
